version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9300"
    volumes:
      - "E:/Others/WTDocker/csvserver-assignment/csvserver/solution/inputFile:/csvserver/inputdata"
    env_file:
      - ./csvserver.env
    environment:
      - CSVSERVER_BORDER=Orange
    restart: always

