version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9300"
    volumes:
      - "E:/Others/WTDocker/csvserver-assignment/csvserver/solution/inputFile:/csvserver/inputdata"
    env_file:
      - ./csvserver.env
    restart: always


  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    restart: always

